services:
  ssaffice-be:
    image: ${DOCKER_IMAGE:-kimhaeyeop/ssaffice-be}:${DOCKER_TAG:-latest}
    container_name: ssaffice-be
    ports:
      - "9090:9090"
    env_file:
      - ./ssaffice-BE/.env
    volumes:
      - ./ssaffice-BE/logs:/app/logs
    depends_on:
      - redis
    restart: unless-stopped

  ssaffice-fe:
    image: ${DOCKER_IMAGE:-kimhaeyeop/ssaffice-fe}:${DOCKER_TAG:-latest}
    container_name: ssaffice-fe
    ports:
      - "443:443"
      - "80:80"
    environment:
      - SERVER_NAME=k11a605.p.ssafy.io
      - BACKEND_HOST=ssaffice-be
      - BACKEND_PORT=9090
    volumes:
      - /etc/letsencrypt/live/k11a605.p.ssafy.io/fullchain.pem:/etc/nginx/ssl/certificate.crt:ro
      - /etc/letsencrypt/live/k11a605.p.ssafy.io/privkey.pem:/etc/nginx/ssl/private.key:ro
      - /etc/letsencrypt/live/k11a605.p.ssafy.io/chain.pem:/etc/nginx/ssl/ca_bundle.crt:ro
    depends_on:
      - ssaffice-be
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  logs:
  redis_data:
