services:
  # Backend Service
  ssaffice-be:
    image: ${DOCKER_IMAGE:-kimhaeyeop/ssaffice-be}:${DOCKER_TAG:-latest}
    container_name: ssaffice-be
    network_mode: "host"
    env_file:
      - ./ssaffice-BE/.env
    environment:
      - TZ=Asia/Seoul
      - SERVER_ADDRESS=0.0.0.0
    volumes:
      - ./ssaffice-BE/logs:/app/logs

  # Frontend Service
  ssaffice-fe:
    image: ${DOCKER_IMAGE:-kimhaeyeop/ssaffice-fe}:${DOCKER_TAG:-latest}
    container_name: ssaffice-fe
    network_mode: "host"
    environment:
      - SERVER_NAME=k11a605.p.ssafy.io
      - BACKEND_HOST=127.0.0.1
      - BACKEND_PORT=9090
      - TZ=Asia/Seoul
    volumes:
      - /etc/letsencrypt/live/k11a605.p.ssafy.io/fullchain.pem:/etc/nginx/ssl/certificate.crt:ro
      - /etc/letsencrypt/live/k11a605.p.ssafy.io/privkey.pem:/etc/nginx/ssl/private.key:ro
      - /etc/letsencrypt/live/k11a605.p.ssafy.io/chain.pem:/etc/nginx/ssl/ca_bundle.crt:ro
    depends_on:
      - ssaffice-be

volumes:
  logs: