### 공지 삭제
DELETE http://localhost:9090/api/notice/1
Content-Type: application/json


### 공지 리스트 조회
GET http://localhost:9090/api/notice?page=0&size=20&sort=createdAt,DESC
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbjJAZ21haWwuY29tIiwiZXhwIjoxNzMxMzE2NjM2fQ.wTA8xgeWD8OyuKE3rPL4EZfJLfBlYeX1Sr9lFzdwWcqgmRmdpeQ_KlVH7_Pw3m7pS1qMBKx4X60-5GBS9fs1hQ