### 공지 추가
POST http://localhost:9090/api/notice
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0NEBnbWFpbC5jb20iLCJleHAiOjE3MzA4NTUzODV9.pb3k9qM4mCzJCzHhYsiRnI2ZodwteHc-CK7-ugtSO52wVP-LnTyOxEyodD-ayAh-H-WMwaUob0RkfhyFvXwOTw

{
  "title": "테스트9",
  "content": "공지사항입니다5",
  "taskTypeCd" : "GENERAL",
  "isEssentialYn" : "N"
}

### 공지 삭제
DELETE http://localhost:9090/api/notice/1
Content-Type: application/json


### 공지 리스트 조회
GET http://localhost:9090/api/notice?page=0&size=20&sort=createdAt,DESC
Content-Type: application/json