### 변수 설정
@scheduleId = 2
@remindId = 4
@JWT = eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbjJAZ21haWwuY29tIiwiZXhwIjoxNzMxNDIzOTI2fQ.NhHWX7vjIbiDtqj9iNLgDIfxYM-_CiCNTOaFcpX_-H2-b2bVgQM6mpUKzpyD78rUEQuZIOpE2v9CWkLJi-Ag1w

### 알림 등록
POST http://localhost:9090/api/schedules/{{scheduleId}}/reminds
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "isEssentialYn": "N",
  "remindTypeCd": "DAILY",
  "remindDateTime" : "2024-11-01T18:00:00"
}

### 알림 삭제
DELETE http://localhost:9090/api/schedules/reminds/{{remindId}}
Content-Type: application/json
Authorization: Bearer {{JWT}}