### 변수 설정
@scheduleId = 15
@JWT = eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbjFAZ21haWwuY29tIiwiZXhwIjoxNzMxODUxNDY4fQ.QHkLJgCyXENQRyt90Oxl8dA-BTEcVcyLuLj9SS_cz9YV3ca55dny_e6MUZSZUK3if-JougkQbvNm-A_7S6uoyQ
@noticeId = 1

### 개인 일정 등록
POST http://localhost:9090/api/schedules
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "title": "개인 일정 테스트4",
  "memo": "개인 일정 테스트4",
  "startDateTime": "2024-11-13T14:44:00",
  "endDateTime": "2024-11-17T18:00:00",
  "scheduleSourceTypeCd": "PERSONAL",
  "remindRequests": [
    {
      "isEssentialYn": "N",
      "remindTypeCd": "ONCE",
      "remindDateTime": "2024-11-07T15:00:00"
    }
  ]
}

### 관리자의 개별 일정 등록
POST http://localhost:9090/api/schedules/admin
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "scheduleRequest": {
    "title": "관리자 개별 일정 테스트4",
    "memo": "관리자 개별 일정 테스트 내용4",
    "startDateTime": "2024-11-13T14:44:00",
    "endDateTime": "2024-11-17T18:00:00",
    "scheduleSourceTypeCd": "TEAM",
    "remindRequests": [
      {
        "isEssentialYn": "N",
        "remindTypeCd": "ONCE",
        "remindDateTime": "2024-11-07T15:00:00"
      }
    ]
  },
  "userIds": [2, 3]
}

### 일정 수정 1
PUT http://localhost:9090/api/schedules/{{scheduleId}}
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "title": "테스트수정1",
  "memo": "테스트내용수정1",
  "startDateTime": "2024-11-01T12:44:00",
  "endDateTime": "2024-11-12T16:00:00",
  "scheduleSourceTypeCd": "PERSONAL",
  "scheduleStatusTypeCd": "IN_PROGRESS",
  "userId": 1,
  "remindRequests": [
    {
      "isEssentialYn": "N",
      "remindTypeCd": "ONCE",
      "remindDateTime": "2024-11-07T15:00:00"
    }
  ]
}

### 일정 수정 2
PUT http://localhost:9090/api/schedules/{{scheduleId}}
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "isEnrollYn": "N"
}

### 일정 조회
GET http://localhost:9090/api/schedules/{{scheduleId}}
Content-Type: application/json
Authorization: Bearer {{JWT}}

### 일정 삭제
DELETE http://localhost:9090/api/schedules/{{scheduleId}}
Content-Type: application/json
Authorization: Bearer {{JWT}}

### [일정 리스트]

### 미등록 공지 조회
GET http://localhost:9090/api/schedules/unregistered
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "isEnrollYn": "N",
  "scheduleStatusTypeCd": null,
  "scheduleSourceTypeCd": null,
  "filterStartDateTime": null,
  "filterEndDateTime": null
}

### 개인 일정 리스트 조회
GET http://localhost:9090/api/schedules
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "isEnrollYn": null,
  "scheduleStatusTypeCd": null,
  "scheduleSourceTypeCd": null,
  "filterStartDateTime": null,
  "filterEndDateTime": null
}

### 관리자의 일정 리스트 조회
GET http://localhost:9090/api/schedules/admin/assigned
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "isEnrollYn": null,
  "scheduleStatusTypeCd": null,
  "scheduleSourceTypeCd": "TEAM",
  "filterStartDateTime": null,
  "filterEndDateTime": null
}
