### 회원가입
POST http://localhost:9090/api/users
Content-Type: application/json

{
  "email": "test4@gmail.com",
  "password": "1234",
  "name": "tester4",
  "roleIds": [
    "ROLE_ADMIN"
  ],
  "cohortNum": 1,
  "regionCd": "SEOUL",
  "classNum": 1,
  "trackCd": "NON_MAJOR_PYTHON"
}